fname = input("\nEnter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
birthday = input("Enter Birth Day: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course: ")
lvl = input("Enter Year Level: ")

print("\nName:",fname,mname,lname,sep=' ')
print("Birthday: "+birthday)
print("Gender: "+gender)
print("Address: "+address)
print("Course: "+course)
print("Year Level: "+lvl)